### ISSUE TITLE
Error send packet, Connection reset

### ISSUE THREAD

**Issue by ToysoftInc** [pedroSG94/RTSP-Server#41] opened 2021-05-25 21:20 UTC
When the server is running for sometime I get this error message.

**"Error send packet, Connection reset"**

Do you know what is the cause and how to automatically restart the server?

I'm running the server on a mobile network and **not** wifi.

Thanks

**Comment by ToysoftInc** [comment] 2021-05-26 14:20
public void onConnectionFailedRtsp(@NonNull String reason) { }

I stop stream.  So i can ignore the error and it will still continue to stream or does the server stop?

**Comment by pedroSG94** [comment] 2021-05-26 14:58
This is ONLY for tests, but try ignore it and let me know if you can connect with other client and reproduce stream without problems.

If you can, this is a bug and should be fixed. If you can't, all is working fine and you should stop and re start server.

No matter the result, report me your tests result

**Comment by ToysoftInc** [comment] 2021-05-26 15:16
When the server gets an error it stops correct and all connecting clients disconnects too?

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/e4252d008facdf0e55689dce1f5df53ac22f634c/rtsp/src/main/java/com/pedro/rtsp/rtsp/RtspSender.kt#L147

btw, one of my user is having this problem so it is hard for me to debug and duplicate the error.

**Comment by pedroSG94** [comment] 2021-05-26 15:36
No, that is when you call stop. For this reason this should be called in onConnectionFailedRtsp.

I mean that maybe this is not a server error. Maybe it is only an error with a client and we can stop that client. For this reason I told you that, to know if this is a server error or client error.

**Comment by linean** [comment] 2022-05-26 11:31
I think I have very similar issue in version `2.1.7`. I call `RtspCamera2.stopStream()` and few milliseconds later I get `onConnectionFailedRtsp: Error send packet, Socket closed`. It only happens from time to time.

**Comment by pedroSG94** [comment] 2022-05-26 22:12
> I think I have very similar issue in version `2.1.7`. I call `RtspCamera2.stopStream()` and few milliseconds later I get `onConnectionFailedRtsp: Error send packet, Socket closed`. It only happens from time to time.

This could be produced because library try to send a packet with the socket already closed (it is a thread sync problem since the thread should die before the socket is closed) but it isn't a big problem. You can control it with a variable using a boolean to know if you called stopStream or not.

Anyway, I will check it to avoid this error as soon as I can and report you the result.

**Comment by linean** [comment] 2022-05-27 07:12
It would be nice to be able attach and detach `connectCheckerRtsp` whenever needed. But I see it's not a simple change.

For e.g.
```
rtspCamera.setConnectChecker(checker)
rtspCamera.startStream(...)

...
rtspCamera.removeConnectChecker()
rtspCamera.stopStream(...)
```

**Comment by pedroSG94** [comment] 2022-05-30 18:36
I will check if this is an useful change.

**Comment by pedroSG94** [comment] 2024-02-26 15:18
The feature is not worth to develop. If you don't need the interface you can ignore methods
Closing as inactive.

**Closed by pedroSG94** 2024-02-26 15:18 UTC
Labels: enhancement
