### ISSUE TITLE
update latest version, exception info: java.lang.ArrayIndexOutOfBoundsException:

### ISSUE THREAD

**Issue by pengxiao18** [pedroSG94/RTSP-Server#140] opened 2024-10-28 08:25 UTC
E  Unexpected error
                                                                                                    java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                                                                                                    	at com.pedro.rtsp.rtsp.RtspSender.setSocketsInfo(SourceFile:38)
                                                                                                    	at com.pedro.rtspserver.server.ServerClient$startClient$1.invokeSuspend(SourceFile:463)
                                                                                                    	at nb.resumeWith(SourceFile:12)
                                                                                                    	at x22.O0(SourceFile:7)
                                                                                                    	at h.resumeWith(SourceFile:14)
                                                                                                    	at nb.resumeWith(SourceFile:48)
                                                                                                    	at l50.run(SourceFile:126)
                                                                                                    	at r11$a.run(SourceFile:4)
                                                                                                    	at rf2.run(SourceFile:3)
                                                                                                    	at wt.e0(SourceFile:1)
                                                                                                    	at wt$c.b(SourceFile:34)
                                                                                                    	at wt$c.m(SourceFile:29)
                                                                                                    	at wt$c.run(SourceFile:1)

**Comment by pengxiao18** [comment] 2024-10-28 09:38
The player I use is org.videolan.android:libvlc-all:3.5.4-eap4.
The Code:

Media media = new Media(libVLC, Uri.parse(rtspUrl));
media.addOption(":network-caching=300"); 
media.setHWDecoderEnabled(true, false);
mediaPlayer.setMedia(media);
mediaPlayer.play();
media.release();

**Comment by pengxiao18** [comment] 2024-10-28 09:40
There is no problem using the previous version:

implementation 'com.github.pedroSG94:RTSP-Server:1.3.1'
implementation 'com.github.pedroSG94.RootEncoder:library:2.5.1'

**Comment by pedroSG94** [comment] 2024-10-28 10:41
Hello,
I detected that it is a problem related to only use a track (only audio or only video)
I'm fixing it

**Comment by pedroSG94** [comment] 2024-10-28 11:51
This should be fixed in version 1.3.3.
Download the last version of the README again and test it.

**Comment by pengxiao18** [comment] 2024-10-28 13:03
I am downloading the new version to test

**Comment by pedroSG94** [comment] 2024-10-28 13:23
Ok, I will check it directly with VLC.
Can you give me the VLC gradle import to reproduce the error?

**Comment by pengxiao18** [comment] 2024-10-28 13:27
implementation 'org.videolan.android:libvlc-all:3.5.4-eap4'

**Comment by pengxiao18** [comment] 2024-10-28 13:31
![42a928459db35ebd490cb9dd1989108](https://github.com/user-attachments/assets/cd9e2651-c926-4fcc-817e-1eb25442302f)

I just debugged and found that videoServerPorts and audioServerPorts are both empty arrays

**Comment by pedroSG94** [comment] 2024-10-28 13:38
Maybe because the server request TCP instead UDP.
Can you share the RTSP commands that should be able in the logcat?

**Comment by pengxiao18** [comment] 2024-10-28 13:42
You are right, I added options.add("--rtsp-tcp") in the vlc playback parameters

**Comment by pengxiao18** [comment] 2024-10-28 13:56
I caught the log
[log.txt](https://github.com/user-attachments/files/17543454/log.txt)

**Comment by pedroSG94** [comment] 2024-10-28 17:27
Hello,

I was able to reproduce it using this command:
```
//open VLC and force use TCP
vlc --rtsp-tcp rtsp://192.168.0.6:1935
```
Test with version 1.3.4
Also, I added a callback for the bitrate in each client and fixed a problem related with the timestamp that few players need to work

**Comment by pengxiao18** [comment] 2024-10-29 02:00
I updated to the latest version and the problem no longer occurs.

But there is a kotlin coroutine exception that occurs once every 5 seconds.

**Comment by pengxiao18** [comment] 2024-10-29 02:02
I updated to the latest version and the problem no longer occurs.

But there is a kotlin coroutine exception that occurs once every 5 seconds.

[log_2024_10_29.txt](https://github.com/user-attachments/files/17550625/log_2024_10_29.txt)

**Comment by pedroSG94** [comment] 2024-10-29 09:51
Hello,

I know about that error but you can ignore it. This issue is temporal fix that I ddid until ktor fix a problem related with timeout, you can ignore that issue because the library works even with that error.

Closing as solved, let me know if you have more problems

**Closed by pedroSG94** 2024-10-29 09:51 UTC
